---

key_name: "{{ vpc_name }}-key"

jenkins_security_groups:
  - sg_name: jenkins-sg
    sg_description: This sg is for app instance
    sg_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "{{ app_port }}"
        to_port: "{{ app_port }}"
        cidr_ip: 0.0.0.0/0

...
