---

- set_fact:
    ansible_python_interpreter: '{{ansible_playbook_python}}' 

- name: Find the current login user
  command: whoami
  register: login_user

- name: EC2Key | Creates an new ec2 key with mentioned name if not present
  ec2_key:
    region: "{{ vpc_region }}"
    name: "{{ key_name }}"
  register: ec2_key

- name: EC2Key | Save the private key
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "./ssh_key/aws-jenkins-private.pem"
    mode: 0600
  when: ec2_key.changed

- name: Jenkins | Create Security Group
  ec2_group:
    name: "{{ item.sg_name }}"
    description: "{{ item.sg_description }}"
    region: "{{ vpc_region }}" # Change the AWS region here
    vpc_id: "{{ vpc.vpc_id }}" # vpc is the resgister name, you can also set it manually
    state: present
    rules: "{{ item.sg_rules }}"
  with_items: "{{ jenkins_security_groups }}"
  register: jenkins_sg

- name: Jenkins | Tag the Security Group with a name
  ec2_tag:
    resource: "{{ item.group_id}}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-{{ item.item.sg_name }}"
  with_items: "{{ jenkins_sg.results }}"

- debug: var=jenkins_sg

...
